import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {buildInquiry,summary,whatsappMessage} from '../public/consulta/model.js';
const id='11111111-1111-4111-8111-111111111111',date='2026-10-03T12:00:00-03:00';
test('three branches export versioned minimal fields',()=>{for(const [service,answers] of Object.entries({EQUIPMENT:{problem:'No enciende'},PARTS:{part:'Memoria RAM'},SOFTWARE:{need:'Sitio web'}})){const inquiry=buildInquiry(service,{name:'Cliente'},answers,id,date);assert.equal(inquiry.version,1);assert.equal(inquiry.schema,'scalaris.inquiry');assert.match(summary(inquiry),/Cliente/);assert.equal(inquiry.contact.phone,'');}});
test('branch switch drops unrelated answers and credentials',()=>{const inquiry=buildInquiry('SOFTWARE',{name:'A',password:'never'},{need:'Sistema',password:'never',problem:'old'},id,date);assert.equal(inquiry.answers.problem,undefined);assert.equal(inquiry.answers.password,undefined);assert.equal(inquiry.contact.password,undefined);});
test('WhatsApp URL is brief and omits entered identity and phone',()=>{const inquiry=buildInquiry('SOFTWARE',{name:'PRIVATE-NAME',phone:'PRIVATE-PHONE'},{need:'x'.repeat(1800)},id,date);const message=whatsappMessage(inquiry);assert.ok(message.length<400);assert.ok(!message.includes('PRIVATE'));});
test('validation requires only useful identity and branch detail',()=>{assert.throws(()=>buildInquiry('SOFTWARE',{name:'A'},{},id,date));assert.throws(()=>buildInquiry('PARTS',{name:'A'},{part:'x'.repeat(2001)},id,date));assert.throws(()=>buildInquiry('EQUIPMENT',{name:''},{problem:'No enciende'},id,date));});
test('form has no personal persistence, network fetch or analytics',()=>{const code=readFileSync(new URL('../public/consulta/form.js',import.meta.url),'utf8');assert.ok(!/localStorage|sessionStorage|fetch\(|sendBeacon|XMLHttpRequest/.test(code));assert.ok(code.includes('wa.me/5491141477227'));});
